### PR TITLE
EVG-16236 use new grip function signature

### PR DESCRIPTION
**Pull request by ybrill**
[EVG-16236](https://jira.mongodb.org/browse/EVG-16236)

Accommodate changes from https://github.com/mongodb/grip/commit/898ba2888109b89e382fe10b1aed1574fe9fe484

### CODE REVIEW

**Review by Kimchelly — COMMENTED** [review]
Should this also upgrade Jasper?

**Comment by ybrill** [comment]
good point! I'll include it here when it merges.
I wonder how the build succeeded. In other words, I thought there's only one version of grip (because we don't use semantic versioning for it). If we use the old one curator would be using the wrong signature and if we use the new one jasper is using the wrong one. So which version could it have used that worked for both?

**Comment by ybrill** [comment]
I would have expected it to fail like [the cedar build](https://spruce.mongodb.com/task/sink_ubuntu_dist_patch_760bb2644e77d393a3c3657045868063fea9988d_620aa8ba0ae6064fc60bac7b_22_02_14_19_08_44/logs?execution=0) failed.

**Comment by ybrill** [comment]
I've updated jasper now.

**Comment by Kimchelly** [comment]
It's because Curator only uses the CLI portion of Jasper, which has no dependence on the buffered sender since it's just a client. Modules only include the necessary code for compilation; it would fail to compile if you added any piece of code that depended on the logging in the `options` package.

**Comment by ybrill** [comment]
Ah, that's smart

**Review by Kimchelly — APPROVED** [review]

**Pull request merged**
